-- local GeneralEntries, SubMenu = MenuEntries['general'], {}

-- local canStartCornering = false
-- local showSellMethOption = false
-- local hasCarTarget = false

-- AddEventHandler("cn:target:changed", function(pEntity, pEntityType)
--   if not pEntity or pEntityType ~= 2 then
--     hasCarTarget = false
--     return
--   end
--   hasCarTarget = true
-- end)

-- AddEventHandler("desirerp-meth:showSellDrugsMenuItem", function(type, b)
--     if type == "cancorner" then
--         canStartCornering = b
--     end
-- end)

-- AddEventHandler("desirerp-polyzone:enter", function(name)
--     if name == "meth_corner" then
--         showSellMethOption = true
--     end
-- end)
-- AddEventHandler("desirerp-polyzone:exit", function(name)
--     if name == "meth_corner" then
--         showSellMethOption = false
--     end
-- end)

-- Citizen.CreateThread(function()
--     GeneralEntries[#GeneralEntries+1] = {
--         data = {
--             id = "sellmeth",
--             icon = "#walking",
--             title = "Sell",
--             event = "desirerp-meth:cornerSellProduct",
--         },
--         isEnabled = function()
--             return not isDead and showSellMethOption and not canStartCornering and hasCarTarget
--         end,
--     }
--     GeneralEntries[#GeneralEntries+1] = {
--         data = {
--             id = "sellmethfromcorner",
--             icon = "#walking",
--             title = "Corner",
--             event = "desirerp-meth:cornerStartSelling",
--         },
--         isEnabled = function()
--             return not isDead and canStartCornering
--         end,
--     }
--     -- for index, data in ipairs(Options) do
--     --     SubMenu[index] = data.data.id
--     --     MenuItems[data.data.id] = {data = data.data, isEnabled = data.isEnabled}
--     -- end
--     -- GeneralEntries[#GeneralEntries+1] = {
--     --     data = {
--     --         id = "methlab",
--     --         icon = "#walking",
--     --         title = "Lab",
--     --     },
--     --     subMenus = SubMenu,
--     --     isEnabled = function()
--     --         return not isDead and inLab
--     --     end,
--     -- }
-- end)

-- -- local function checkObject(obj)
-- --     return function()
-- --         return not isDead and inLab and targetObject == obj
-- --     end
-- -- end

-- -- local Options = {
-- --     {
-- --         data = {
-- --             id = 'desirerp-meth:startCooking',
-- --             title = "Start Cooking",
-- --             icon = "#police-check",
-- --             event = "desirerp-meth:startCooking",
-- --         },
-- --         isEnabled = checkObject("computer"),
-- --     },
-- --     {
-- --         data = {
-- --             id = 'desirerp-meth:adjustFridgeTemp',
-- --             title = "Adjust Temperature",
-- --             icon = "#police-check",
-- --             event = "desirerp-meth:adjustFridgeTemp",
-- --         },
-- --         isEnabled = checkObject("fridge"),
-- --     },
-- --     {
-- --         data = {
-- --             id = 'desirerp-meth:adjustSteamLevel',
-- --             title = "Adjust Levels",
-- --             icon = "#police-check",
-- --             event = "desirerp-meth:adjustSteamLevel",
-- --         },
-- --         isEnabled = checkObject("distil"),
-- --     },
-- --     {
-- --         data = {
-- --             id = 'desirerp-meth:adjustDistilSettings',
-- --             title = "Adjust Settings",
-- --             icon = "#police-check",
-- --             event = "desirerp-meth:adjustDistilSettings",
-- --         },
-- --         isEnabled = checkObject("distil"),
-- --     },
-- --     {
-- --         data = {
-- --             id = 'desirerp-meth:adjustMixerTemp',
-- --             title = "Adjust Temperature",
-- --             icon = "#police-check",
-- --             event = "desirerp-meth:adjustMixerTemp",
-- --         },
-- --         isEnabled = checkObject("mixer_temperature"),
-- --     },
-- --     {
-- --         data = {
-- --             id = 'desirerp-meth:addIngredient',
-- --             title = "Add Ingredient",
-- --             icon = "#police-check",
-- --             event = "desirerp-meth:addIngredient",
-- --         },
-- --         isEnabled = checkObject("mixer_drop"),
-- --     },
-- --     {
-- --         data = {
-- --             id = 'desirerp-meth:adjustMixerSettings',
-- --             title = "Adjust Settings",
-- --             icon = "#police-check",
-- --             event = "desirerp-meth:adjustMixerSettings",
-- --         },
-- --         isEnabled = checkObject("mixer_settings"),
-- --     },
-- --     {
-- --         data = {
-- --             id = 'desirerp-meth:pickupIngredient',
-- --             title = "Pickup",
-- --             icon = "#police-check",
-- --             event = "desirerp-meth:pickupIngredient",
-- --         },
-- --         isEnabled = checkObject("ingredient"),
-- --     },
-- -- }


